exception_details/__init__.py,sha256=iqtVcmPoKI44_xmhyp5qliJA3T3C0ZLxa51QWiR_4pk,350
exception_details/_version.py,sha256=Qu9opGoql-p9L0nl3Kk9BVupqZEeA1F-2L6A9bMYZ8E,518
exception_details/exception_details.py,sha256=GmfRzuXv4CyNcRHS9kdAsbYHLK_4mrfnXPE9ebhU0TE,9389
exception_details/test.py,sha256=iNvmpGweP3N4MaddtZx8WbaCeh55ytXHKUqsVwNSiLc,2257
exception_details-0.0.3.dist-info/licenses/LICENSE,sha256=9HsmUbkMFZDTY_7eyGX6_7F-jwhNF1PxA_6J37d5YPA,1095
exception_details-0.0.3.dist-info/METADATA,sha256=ZGm-tUXILV9jbkaV8ToePDCokLJYZsdznFpv2aM7_Ao,2761
exception_details-0.0.3.dist-info/WHEEL,sha256=pxyMxgL8-pra_rKaQ4drOZAegBVuX-G_4nRHjjgWbmo,91
exception_details-0.0.3.dist-info/top_level.txt,sha256=oI-s3hCBa08Bax10Tt2Du6FiUdeo6FzFjHYv6bjEEpk,18
exception_details-0.0.3.dist-info/RECORD,,
